### PR TITLE
SECURITY KEY:  updated styling for security key table

### PR DESCRIPTION
**Pull request by eunjuhuss**
#### Description:
old security key table was unreadable in mobile mode and not balanced in the desktop mode.
[Figma design]( https://www.figma.com/file/IBBTDRxd5dKQa7Ltj0Hd0l/eduID%3A-website-user-flow?node-id=179%3A580)
I followed confirmed design. however spacing between columns is not exactly same as design because I used percentage of columns.

#### Summary:
- Added className for table headings and width
  `security-name: 36%`,
  `security-creation-date: 21%`, 
 `security-last-used-date: 21%`,
 `security-verify-link: 17%`, 
 `security-remove-data: 5%`

-  Display: none `security-creation-date` and `security-last-used-date` @ max-width: 568px
-  when Security Key name is too long, text will be cropped  and will display followed by dots.

`   white-space: nowrap;`
`   text-overflow: ellipsis;`
`   overflow: hidden;`

-----
**Before and After (@1200px)**
Screenshot 2020-10-26 at 14 45 22

**Before and After (@320px)**
Screenshot 2020-10-26 at 14 45 39

-----

#### For reviewer:
- [x] Read the above description
- [x] Reviewed the code changes
- [x] Navigate to the branch (pulled the latest version)
- [x] Run the code and been able to execute the expected function
- [x] Check any styling on both desktop and mobile sizes

### CODE REVIEW

**Review by njons — COMMENTED** [review]
I think we should make the table headings look the same as labels - to visually separate data from the label?

**Comment by eunjuhuss** [comment]
I changed table heading styling to the same as label. It looks much cleaner. Thanks for the tips. Regarding to grid, for now personally Im satisfied with table. 

----
Screenshot 2020-10-28 at 11 17 05

Screenshot 2020-10-28 at 11 17 21

----

**Comment by njons** [comment]
In the other tables (email/phone) we use gray/black to signal if data is verified or not, is there are reason as to why were not using that standard here? 

I think we would also gain a lot from setting a min size for all static data (dates, cancel button and maybe even the "verify/verifierad" button at its largest size) to give more room to the name column and also to prevent the data from breaking while scaling down.

**Comment by eunjuhuss** [comment]
>  In the other tables (email/phone) we use gray/black to signal if data is verified or not, is there are reason as to why were not using that standard here?

I can update accordingly.

> I think we would also gain a lot from setting a min size for all static data (dates, cancel button and maybe even the "verify/verifierad" button at its largest size) to give more room to the name column and also to prevent the data from breaking while scaling down.

I tried earlier and I was now happy with how it look. in mobile mode name text only gained one letter and verify key and remove icon became too close. in desktop mode, verify key displays in two rows. even in tablet mode, all columns became too close to each other. 


> Please also log somewhere that these changes impact the other tables:

I checked in my environment with safari and chrome however I can't see any changes on the other (phone/emai) tables

**Comment by eunjuhuss** [comment]
Updated styling for verified / not verified security key

- Security key is not verified
Screenshot 2020-10-29 at 13 31 54

- Security key is verified
Screenshot 2020-10-29 at 13 31 21

**Pull request merged**
