### PR TITLE
RESETPASSWORD: Add styling and translate text for extra security

### PR DESCRIPTION
**Pull request by eunjuhuss**
#### Description:
Add styling and translate text for extra security(sms/security key) and rendering extra security button depending on what extra security options the user has configured

#### Summary:
- Changed from `import i18n` to` InjectIntl` to have the same root as Login 
- Moved translated text from `login.js/json` to `password.js/json`
- Added translate text for extra security
- map loop for rendering of extra security buttons
---
- Extra security via sms (English / Swedish)
Screenshot 2021-06-18 at 11 28 18
Screenshot 2021-06-18 at 11 45 04

- Extra security with security key (English / Swedish)
Screenshot 2021-06-18 at 11 28 48
Screenshot 2021-06-18 at 11 39 47

---

#### For reviewer:
- [ ] Read the above description
- [ ] Reviewed the code changes
- [ ] Navigate to the branch (pulled the latest version)
- [ ] Run the code and been able to execute the expected function
- [ ] Check any styling on both desktop and mobile sizes

### CODE REVIEW

**Comment by johanlundberg** [comment]
In the browser that asks for Swedish I get the pages in English with an option to translate to English.
When I click the translation button I get English again but now an option to translate to Swedish, and the third press of the button I actually get Swedish.

image

**Comment by johanlundberg** [comment]
I would say that "Bevisa att du är ägaren till eduID med din extra säkerhet." sounds better as "Bevisa att du är ägaren till kontot." same for the English version "Prove that your are the owner of eduID with your extra security." -> "Prove that your are the owner of the account."

**Comment by johanlundberg** [comment]
There seems like there is only one option showing up as extra security with preference for SMS. The user should be able to choose if the account has both a verified phone number and a security key. If not both options should be visible at the same time I would prefer security key as the first option.

**Review by johanlundberg — COMMENTED** [review]
Added comments in the Conversation-tab.

**Review by johanlundberg — COMMENTED** [review]
When the state has expired and backend returns resetpw.state-not-found a generic error is shown. This should probably be handled and a better error message should be showed.

**Comment by johanlundberg** [comment]
The Swedish translation now says "Extra äkerhet" missing s.
image

**Comment by johanlundberg** [comment]
The layout of more than one phone number should be improved.
image

**Comment by eunjuhuss** [comment]
- fixed missing "s" for extra security in swedish
- improved layout for more than one phone number 
- added translate text for "resetpw.state-not-found", "resetpw.expired-email-code"
- change primary selection option to "security key" instead of "security with sms"

----
Screenshot 2021-06-23 at 12 28 31

---

**Review by johanlundberg — APPROVED** [review]

**Pull request merged**
